export { default as Arduino } from './arduino.js';
export { default as HTML } from './html.js';
export { default as JSX } from './jsx.js';
export { default as Nginx } from './nginx.js';
export { default as Python } from './python.js';
export { default as Ruby } from './ruby.js';
export { default as SCSS } from './scss.js';
export { default as Shell } from './shell.js';
import '../grammar.js';
import '../utils-8b837a1b.js';
import '../template.js';
import '../utils/verbose-regexp.js';
import '../context.js';
import '../lexer.js';
